dataformCoreVersion: 3.0.24
defaultProject: drawingfire-b72a8
defaultLocation: europe-west2
defaultDataset: dataform
vars: {
    "tableDescription": "something amazing",
    "dummyColumnValue": "43"
}
defaultAssertionDataset: dataform_assertions
